### ISSUE TITLE
Prova segnalazione 1

### ISSUE THREAD

**Issue by c83n** [c83n/prova_tci_learning#1]
Contenuto che deve avere la segnalazione

tel: +393666373172
email: francesco.izzi@gmail.com
cosa: Segnalazione di test 3
descrizione: asdasda
indirizzo: Viale Emilio Maraini, 02100 Rieti RI, Italia
lat: 42.404509
lon: 12.856728100000055
link: 
data: 06/09/2016

Occorre inserire le coordinate 
lat: 
lon:
se lo fai da qui le devi scrivere a mano

Label di default
- posso creare label
- avremo lista label ufficiali
- ma posso fare label di prova per capire

Assegno label
Le label sono FONAMENTALI
- se mettiamo codice approvato il csv che pesca da qui la prende e vice versa
- e lui mi mette cronologia sotto

CLOSED
- La redazione dovrà guardarne un botto

LOCK CONVERSATION
- Solo collaboratori
- No commentatori

MILESTONE
- ci ragionano loro

LOCK CONVERSATION

**Comment by fizzi** [comment]
Attenzione alle coordinate!

**Comment by fizzi** [comment]
Ok aiuto inviato al UCL xxx

**Comment by c83n** [comment]
Contattato segnalazione problema risolto
