### ISSUE TITLE
Prova per geni

### ISSUE THREAD

**Issue by chiccap** [c83n/prova_tci_learning#2]
proviamo a conquistare github!
lat: 1
lon: 2

**Comment by c83n** [comment]
freddie 4 president

**Comment by c83n** [comment]
Ma scusa, questa non potrebbe andare anche con label PUZZONE?

**Comment by chiccap** [comment]
il servizio puzzolente dice che ho ragione io e che va in label question.

**Comment by c83n** [comment]
Ok bella :)
