### ISSUE TITLE
Aiuto richiesto 

### ISSUE THREAD

**Issue by veronicaboggini** [c83n/prova_tci_learning#5]
Aiuto campo spontaneo Capricchia
Lat: 
Lon:

Necessità materassi

**Comment by c83n** [comment]
vero ma questa roba è la stessa che abbiamo mandato al gus l'altro ieri?

**Comment by veronicaboggini** [comment]
Si è la stessa

**Comment by c83n** [comment]
allora direi di approvarla e di mettere label "psico"

**Comment by c83n** [comment]
Ok adesso credo che gli smanettoni quando la chiudiamo la mandano al GUS in automatico

**Comment by c83n** [comment]
Ok i tipi del gus mi dicono che hanno ricevuto quindi la possiamo chiudere
